language: objective-c
before_install:
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake spec
